In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("sarees.csv")

In [4]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,19698082,Mitera,Women Cream-Coloured & Green Floral Silk Blend...,3.5,6,2599.0,68.0,"""₹2,599.00""",INR,http://assets.myntassets.com/assets/images/196...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fabric Qual...",NaN,"[{""size"":""Onesize""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",sarees
1,17314272,Saree mall,Mint Green & Gold Solid Linen Blend Taant Sarees,3.4,12,4799.0,73.0,"""₹4,799.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sarees
2,21425266,Satrani,Woven Design Zari Banarasi Saree,3.6,242,4699.0,74.0,"""₹4,699.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":47,""2_stars"":21,""3_stars"":29,""4_star...","[{""percentage"":""57"",""value_name"":""Fabric Quali...",NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sarees
3,18462146,KALINI,Women Navy Blue Sarees,3.4,10,1599.0,60.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fabric Qual...",NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sarees
4,18465340,Silk Land,Beige & Orange Floral Printed Pure Cotton Jamd...,4.1,15,4125.0,70.0,"""₹4,125.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sarees

In [5]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
17,16287764,Saree mall,Purple Silk Cotton Banarasi Saree,4.1,129,4799.0,72.0,"""₹1,343.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":12,""2_stars"":5,""3_stars"":10,""4_stars...",NaN,AAR███LIF███YLE█████████LIM██████,"[{""size"":""Onesize""}]",NaN,"B-4███,40███402█████████36,███████████████████...","[{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sarees
18,14975360,KALINI,Yellow & Green Ethnic Motifs Fusion Saree,3.9,1194,2396.0,75.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/149...,...,"{""1_star"":140,""2_stars"":73,""3_stars"":139,""4_st...","[{""percentage"":""53"",""value_name"":""Fabric Quali...",VB ███ort███,"[{""size"":""Onesize""}]",NaN,"602███Nid███an █████████, N███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sarees
19,19233030,Satrani,Blue & Gold-Toned Woven Design Zari Silk Cotto...,0.0,0,4612.0,74.0,"""₹1,199.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SAT███I F███ION███,"[{""size"":""Onesize""}]",NaN,700███Hin███tan█████████Cen███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sarees
20,19823504,VAIRAGEE,Black Embellished Sequinned Celebrity Saree,4.2,19,9995.0,83.0,"""₹1,699.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fabric Qual...",Viv███ In███nat██████,"[{""size"":""Onesize""}]",NaN,201███ew ███dar█████████mar███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sarees
21,19305196,MARGI DESIGNERS,Green & Gold-Toned Woven Design Zari Art Silk ...,0.0,0,4499.0,62.0,"""₹1,709.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,M S███PER███ CO█████████RVI██████,"[{""size"":""Pack""}]",NaN,402███4TH███OOR█████████aga███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sarees

In [6]:
df.shape

(22, 24)

In [7]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              22 non-null     int64
 1   title                   22 non-null     str
 2   product_description     22 non-null     str
 3   rating                  22 non-null     float64
 4   ratings_count           22 non-null     int64
 5   initial_price           22 non-null     float64
 6   discount                22 non-null     float64
 7   final_price             22 non-null     str
 8   currency                22 non-null     str
 9   images                  22 non-null     str
 10  delivery_options        22 non-null     str
 11  product_details         22 non-null     str
 12  breadcrumbs             22 non-null     str
 13  product_specifications  22 non-null     str
 14  amount_of_stars         22 non-null     str
 15  what_customers_said     7 non-null      str
 16  seller_name             17 non-null     str
 17  sizes                   22 non-null     str
 18  videos                  0 non-null      float64
 19  seller_information      17 non-null     str
 20  variations              22 non-null     str
 21  best_offer              22 non-null     str
 22  more_offers             22 non-null     str
 23  category                22 non-null     str
dtypes: float64(4), int64(2), str(18)
memory usage: 4.3 KB

In [9]:
df.describe()

,product_id,rating,ratings_count,initial_price,discount,videos
count,2.200000e+01,22.000000,22.000000,22.000000,22.000000,0.0
mean,1.752238e+07,2.104545,92.136364,4582.272727,73.181818,NaN
std,1.575838e+06,1.979052,262.262735,1722.660102,4.895444,NaN
min,1.497536e+07,0.000000,0.000000,1599.000000,60.000000,NaN
25%,1.628775e+07,0.000000,0.000000,4099.000000,72.000000,NaN
50%,1.729235e+07,3.400000,8.000000,4349.000000,74.500000,NaN
75%,1.846454e+07,3.975000,17.250000,4799.000000,76.000000,NaN
max,2.142527e+07,4.200000,1194.000000,9995.000000,83.000000,NaN

In [10]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       15
seller_name                5
sizes                      0
videos                    22
seller_information         5
variations                 0
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [11]:
df = df.dropna()

In [12]:
df.shape

(0, 24)

In [13]:
df = df.drop_duplicates()

In [14]:
high_rated = df[df["rating"] > 4]

high_rated.head()

Empty DataFrame
Columns: [product_id, title, product_description, rating, ratings_count, initial_price, discount, final_price, currency, images, delivery_options, product_details, breadcrumbs, product_specifications, amount_of_stars, what_customers_said, seller_name, sizes, videos, seller_information, variations, best_offer, more_offers, category]
Index: []

[0 rows x 24 columns]

In [15]:
df[["title", "rating", "initial_price", "discount"]]

Empty DataFrame
Columns: [title, rating, initial_price, discount]
Index: []

In [16]:
df["discounted_amount"] = df["initial_price"] * (df["discount"] / 100)

In [17]:
df[["title", "initial_price", "discount", "discounted_amount"]].head()

Empty DataFrame
Columns: [title, initial_price, discount, discounted_amount]
Index: []

In [18]:
df.to_csv("cleaned_sarees.csv", index=False)